images:
  - name: trivy
    type: image
    source: dockerhub
    owner: aquasec
    repo: trivy
    tag: 0.56.1
    semantic: true
  - name: trivy-db
    type: oci
    source: public.ecr.aws
    owner: aquasecurity
    repo: trivy-db
    tag: 2
    semantic: false