images:
  - name: trivy
    type: image
    source: docker.io
    owner: aquasec
    repo: trivy
    semantic: true
  - name: trivy-db
    type: oci
    source: public.ecr.aws
    owner: aquasecurity
    repo: trivy-db
    semantic: false
  - name: semgrep
    type: image
    source: docker.io
    owner: returntocorp
    repo: semgrep
    semantic: true