name:  Semgrep SAST
description: Semgrep SAST
author: 'Kong'
inputs:
  additional_config:
    description: 'Provide additional config to semgrep ci command using --config'
    required: false
    default: ''
  codeql_upload:
    description: 'Toggle to upload results to Github code scanning for public repositories'
    required: false
    default: true
    type: choice
    options:
    - 'true'
    - 'false'
  fail_on_findings:
    description: 'Fail build / job on semgrep findings/errors'
    required: false
    default: false
    type: choice
    options:
    - 'true'
    - 'false'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.12'

    - name: Install dependencies
      shell: bash
      run: pip install -r $GITHUB_ACTION_PATH/requirements.txt

    - name: SAST Scan
      id: semgrep
      shell: bash
      continue-on-error: true
      env:
        ADDITIONAL_CONFIG: ${{ inputs.additional_config }}
      run: |
        semgrep ci --config auto --text --text-output semgrep_${{github.sha}}.txt --sarif -o semgrep_${{github.sha}}.sarif --no-autofix ${{env.ADDITIONAL_CONFIG}}

    # Upload grype cve reports
    - name: Upload Semgrep to Workflow
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: semgrep_sast.zip
        path: |
          semgrep_${{github.sha}}.sarif
          semgrep_${{github.sha}}.txt
        if-no-files-found: warn

    - name: Upload SARIF to Github Code Scanning
      if: ${{ always() && inputs.codeql_upload == 'true' && github.event.repository.visibility == 'public' }}
      uses: github/codeql-action/upload-sarif@51f77329afa6477de8c49fc9c7046c15b9a4e79d # v3.29.7
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: semgrep_${{github.sha}}.sarif
        # Optional category for the results
        # Used to differentiate multiple results for one commit
        category: sast_semgrep

    - name: Print Semgrep Output Findings to Console
      shell: bash
      run: |
        echo "::group::Semgrep Findings"
        # Check if the file exists and is not empty before printing
        if [ -s "semgrep_${{github.sha}}.txt" ]; then
          echo "Semgrep Findings:"
          cat "semgrep_${{github.sha}}.txt"
        else
          echo "No findings detected by Semgrep."
        fi
        echo "::endgroup::"

    - name: Fail on findings
      if: ${{ always() && inputs.fail_on_findings == 'true' && steps.semgrep.outcome == 'failure' }}
      shell: bash
      run: |
        echo "::error::Semgrep has detected findings. For findings, check workflow artifact: semgrep_sast.zip / Github Security analysis"
        exit 1