name: TruffleHog Secret Scanning
description: Detect secrets in code using TruffleHog
author: 'Kong'
inputs:
  fail_on_findings:
    description: 'Fail job if TruffleHog detects findings/secrets'
    required: true
    default: false

runs:
  using: 'composite'
  steps:
    # Dynamically set TRUFFLEHOG_LOG_LEVEL based on env from downstream workflow
    # - If the downstream workflow sets ACTIONS_STEP_DEBUG=true, use trace mode (5)
    # - Else, use info level (0) for quieter logs
    - name: Set TRUFFLEHOG_LOG_LEVEL
      shell: bash
      run: |
        if [[ "$ACTIONS_STEP_DEBUG" == "true" ]]; then
          echo "TRUFFLEHOG_LOG_LEVEL=5" >> $GITHUB_ENV
        else
          echo "TRUFFLEHOG_LOG_LEVEL=0" >> $GITHUB_ENV
        fi

    - name: Running Secret Scan using Trufflehog 
      id: trufflehog 
      uses: trufflesecurity/trufflehog@a05cf0859455b5b16317ee22d809887a4043cdf0 # v3.90.2
      continue-on-error: true 
      with:  
        extra_args: --log-level=${{ env.TRUFFLEHOG_LOG_LEVEL }} --results=verified,unknown

    # Fail the job if secrets are found and fail_on_findings is true
    # The scanner will update the pull request diff view with specific callouts of any credentials that are present
    - name: Fail on TruffleHog Findings
      if: ${{ always() && inputs.fail_on_findings == 'true' && steps.trufflehog.outcome == 'failure' }}
      shell: bash
      run: |
        echo "::error::TruffleHog detected secrets"
        exit 1
