name:  Semgrep SAST CI
description: Semgrep SAST CI
author: 'Kong'
runs:
  using: 'composite'
  steps:

    - name: Semgrep SAST Scan
      uses: docker://returntocorp/semgrep
      with:
        args: "semgrep ci --config auto --sarif -o semgrep_${{github.sha}}.sarif --suppress-errors --no-autofix"

    - name: Upload SARIF file
      if: ${{ github.event.repository.visibility == 'public' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: semgrep_${{github.sha}}.sarif
        # Optional category for the results
        # Used to differentiate multiple results for one commit
        category: sast_semgrep