name: Cleanup PR preview packages
description: Deprecate and unpublish PR preview package versions for closed PRs
inputs:
  package:
    description: Package to cleanup PR versions
    required: true
  days:
    description: Only clean up the versions that are days-to-cleanup newer
    default: 40
  openPRs:
    description: List of open PRs in the repo


runs:
  using: composite
  steps:
    - name: Get PR Info
      shell: bash
      run: |
        pkgName=${{ inputs.package }}
        openPRs=${{ inputs.openPRs }}

        echo " "
        echo "package: ${pkgName}"
        echo "openPRs: ${openPRs}"

        oldestDate=$(date -d '-${{ inputs.days }} day' +%s)
        echo "oldestDate:${oldestDate}"

        current=1
        canDelete="true"

        # get the list of the "-pr." published version for the packages
        pkgDetails=$(npm view "${pkgName}" --json)
        echo "pkgDetails:"${pkgDetails}
        prVersions=($(echo ${pkgDetails} | jq -r '.time' | jq -r 'to_entries' | jq --arg jq_oldestDate ${oldestDate} '[.[] | select(.value |.[0:19] +"Z" | fromdateiso8601 > ($jq_oldestDate|tonumber))]' | jq '[.[] | .key]'| grep "\-pr." | tac | sed 's/[,\"]//g'))
        echo "prVersions:"${prVersions[@]}
        if [[ -z "${prVersions}" ]]; then
          echo "No preview versions found, exiting..."
          exit 0
        fi

        distTags=$(echo ${pkgDetails}|jq -r '."dist-tags"')
        echo "distTags:"${distTags[@]}
        total="${#prVersions[@]}"

        for verToRemove in "${prVersions[@]}"
        do
          echo " "
          echo "$((current++))/${total}"

          if [[ -z "$(echo ${pkgDetails} | jq -r '.versions'|grep ${verToRemove})" ]]; then
            echo "Version already removed, skip..."
            continue
          fi

          verDetails=$(npm view "${pkgName}@${verToRemove}" --json)

          # validate that the version doesn't belong to open PR
          echo "${pkgName}@${verToRemove}"
          prNumber=$(echo ${verToRemove} | sed 's/.*\-pr\.//g'| cut -d'.' -f 1)

          if [[ ! -z $(echo ${openPRs} | sed 's/\"//g'| sed 's/\[/,/g' | sed 's/\]/,/g' | grep ",${prNumber},") ]]; then
            if [[ ! -z $(echo ${distTags}|grep "${verToRemove}") ]]; then
              echo "${pkgName}@${verToRemove}: belongs to open PR and tagged as PR preview, skip..."
              continue
            fi
          fi

          if [[ $(echo ${verDetails}|jq -r ".deprecated") == null ]]; then
            if [[ ! -z $(echo ${distTags}|grep "${verToRemove}") ]]; then
              # remove dist tag if present
              echo "${pkgName}@${verToRemove}: remove dist tag"
              npm dist-tag rm "${pkgName}" "pr-${prNumber}" || true
            fi

            # deprecate and unpublish version, ignore error
            echo "*** deprecating: ${pkgName}@${verToRemove}"
            res=$(npm deprecate "${pkgName}@${verToRemove}" "Deprecated PR preview" 2>&1 || true)
            echo "deprecate:>>>>${res}<<<<"
            if [[ ! -z $(echo "${res}"|grep " E429") ]]; then
              echo "Rate limit reached, exiting..."
              exit 1
            fi

          else
              echo "*** ${pkgName}@${verToRemove}: already deprecated, skip..."
          fi

          if [[ "${canDelete}" == "true" ]]; then
            echo "*** unpublishing: ${pkgName}@${verToRemove}"
            res=$(npm unpublish --force "${pkgName}@${verToRemove}" 2>&1 || true)
            echo "unpublish:>>>>>${res}<<<<"
            if [[ ! -z $(echo "${res}"|grep " E429") ]]; then
              echo "Rate limit reached, exiting..."
              exit 1
            fi

            # NPMJS does not allow to delete specific version if
            # any other version of the package is dependant of other package.
            # So we wont try to unpublish if we detect 405 response once
            if [[ ! -z $(echo "${res}"|grep " E405") ]]; then
              echo "error 405 detected, skip unpublish attempts..."
              canDelete="false"
            fi
          else
            echo "unpublish skipped ..."
          fi

        done
