name: Login to Kong Cloud Accounts
description: Step to authenticate to Kong Cloud Accounts
author: 'Kong'

runs:
  using: composite
  steps:
  # Configure credentails to login into AWS Cloud Account
  # TODO: Update AWS Account & IAM Role Details
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    id: creds
    with:
      aws-region: us-east-1
      role-to-assume: arn:aws:iam::AWS-ACCOUNT-ID-PLACEHOLDER:role/ECR-ROLE-PLACEHOLDER
      role-session-name: GitHub_to_AWS_via_FederatedOIDC

  # To Authenticate client to ECR
  # TODO: Update AWS Account & IAM Role Details
  - name: Login to ECR
    uses: docker/login-action@v3
    with:
      registry: AWS-ACCOUNT-ID-PLACEHOLDER.dkr.ecr.REGION-PLACEHOLDER.amazonaws.com
      username: ${{ steps.creds.outputs.aws-access-key-id }}
      password: ${{ steps.creds.outputs.aws-secret-access-key }}
