name: 'CIS Scan'
description: 'Run CIS compliance scan on Target repositories'
author: 'Kong'

inputs:
  github_token:
    description: 'GitHub token with appropriate permissions for Legitify scan'
    required: true
  repositories:
    description: 'Comma-separated list of repositories to scan (e.g., "owner/repo1,owner/repo2")'
    required: true
  codeql_upload:
    description: 'Upload results to GitHub Code Scanning'
    required: false
    default: false
  scorecard:
    description: 'Enable OpenSSF Scorecard integration'
    required: false
    default: 'no'
  artifact_name:
    description: 'Name for the artifact containing scan results'
    required: false
    default: 'legitify-cis-scan-results'


runs:
  using: 'composite'
  steps:
    - name: Run Legitify GH CIS Scan
      id: legitify-scan
      uses: Legit-Labs/legitify@038aa49473a6974a3ef79f6c76b949b689d23282
      continue-on-error: true
      with:
        github_token: ${{ inputs.github_token }}
        repositories: ${{ inputs.repositories }}
        upload_code_scanning: ${{ inputs.codeql_upload }}
        scorecard: ${{ inputs.scorecard }}
    

    - name: Check if output files exist
      id: legitify-reports
      if: ${{ steps.legitify-scan.conclusion == 'success' }}
      shell: bash
      run: |
        if ls legitify-output.* 1> /dev/null 2>&1; then
          echo "files_exist=true" >> $GITHUB_OUTPUT
          echo "::notice::Legitify output files found"
          ls -la legitify-output.*
        else
          echo "files_exist=false" >> $GITHUB_OUTPUT
          echo "::warning::No Legitify output files found"
        fi

    - name: Upload outputs as Workflow Artifacts
      if: ${{ steps.legitify-scan.conclusion == 'success' && steps.legitify-reports.outputs.files_exist == 'true' }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ${{ inputs.artifact_name }}
        path: legitify-output.*
        if-no-files-found: warn

    - name: Upload SARIF as Code Scanning Results
      if: ${{ inputs.codeql_upload == 'true' && steps.legitify-reports.outputs.files_exist == 'true' && github.event.repository.visibility == 'public' }}
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@51f77329afa6477de8c49fc9c7046c15b9a4e79d # v3.29.7
      with:
        sarif_file: legitify-output.sarif
        category: "legitify-report-${{ github.run_id }}"