name: Build JS SDK
description: >
  This action builds a JavaScript SDK and updates an existing PR with the generated files
runs:
  using: composite
  steps:
    - name: Checkout current repo
      uses: actions/checkout@v3
      with:
        path: sdk
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Checkout OpenAPI Tools
      uses: actions/checkout@v3
      with:
        repository: kong/openapi-generator-config
        path: openapi-generator-config

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
        registry-url: "https://registry.npmjs.org"

    - name: Install Dependencies
      shell: bash
      run: |
        npm install -g @openapitools/openapi-generator-cli@2.5.2

    - name: Create generator config
      shell: bash
      working-directory: sdk
      run: |
        shopt -s extglob
        rm -r !(openapi.yaml)
        cp ../openapi-generator-config/openapitools-js.json openapitools.json
        cp -r ../openapi-generator-config/templates-js .

    - name: "Generate Node SDK"
      shell: bash
      working-directory: sdk
      run: |
        openapi-generator-cli generate --generator-key client

    - name: "Clean up generator files"
      shell: bash
      working-directory: sdk/src
      run: |
        rm -rf openapitools.json templates-js .openapi-generator-ignore .openapi-generator git_push.sh

    - name: Commit SDK changes to the PR
      uses: EndBug/add-and-commit@v9
      with:
        cwd: sdk
        add: src
        default_author: github_actions
        message: Update SDK based on openapi.yaml changes
