name:  Rust Clippy
description: Rust Linting using Clippy
author: 'Kong'
inputs:
  manifest_dir: 
    description: 'Rust Manifest Directory'
    required: false
    default: '.'
  token: 
    description: 'Github token to annotate files with findings'
    required: true

runs:
  using: composite
  steps:
  
    - uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
      with:
        toolchain: stable
        components: clippy

    - name: Set Job Metadata
      shell: bash
      id: meta
      env:
        manifest_dir: ${{ inputs.manifest_dir }}
      run: $GITHUB_ACTION_PATH/scripts/set-env.sh
    
    - uses: Swatinem/rust-cache@81d053bdb0871dcd3f10763c8cc60d0adc41762b # v1

    - uses: actions-rs/clippy-check@b5b5f21f4797c02da247df37026fcd0a5024aa4d # v1
      continue-on-error: true
      with:
        token: ${{ inputs.token }}
        # Explicitly report all findings as warnings to not fail the reporiting status check
        args: --manifest-path ${{ steps.meta.outputs.manifest_path }} -- -W clippy::correctness -W clippy::cargo -W clippy::suspicious -W clippy::style
        name: Rust Clippy Report

    # - uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
    #   continue-on-error: true
    #   with:
    #     command: install
    #     args: "clippy-sarif sarif-fmt"

    # - name: Run Cargo Clippy
    #   shell: bash
    #   continue-on-error: true
    #   run: |
    #     cargo clippy --manifest-path ${{ steps.meta.outputs.manifest_path }} --message-format=json -- -W clippy::correctness -W clippy::cargo -W clippy::pedantic | clippy-sarif | tee rust_clippy_${{github.sha}}.sarif | sarif-fmt

    # - name: Upload Rust Linting SARIF file to CodeQL
    #   if: ${{ github.event.repository.visibility == 'public' }}
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: rust_clippy_${{github.sha}}.sarif
    #     category: clippy_rust
   
    # - name: Upload Rust Linting results to workflow
    #   if: always()
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: rust_clippy_results.sarif
    #     path: |
    #       rust_clippy_${{github.sha}}.sarif
    #     if-no-files-found: warn 
    
    # # Rust Clippy - Linting report
    # - name:  Rust Linting Report - SARIF
    #   shell: bash
    #   run: |
    #     cat rust_clippy_${{github.sha}}.sarif
