name: Build JS SDK
description: >
  This action builds a JavaScript SDK and updates an existing PR with the generated files
inputs: 
  dry-run:
    description: 'If true, the action will not push the changes to the PR'
    required: false
    default: 'false'
  token:
    description: 'A Github Token'
    required: true
  app_directory:
    description: 'The directory of the app to be built'
    required: true
  sdk_output_directory:
    description: 'The directory where the SDK will be generated'
    required: false
    default: 'sdk'
runs:
  using: composite
  steps:
    - name: Enter the app directory
      shell: bash
      run: |
        cd ${{ inputs.app_directory }}
    - name: Checkout OpenAPI Tools
      uses: actions/checkout@v3
      with:
        repository: kong/openapi-generator-config
        path: openapi-generator-config
        token: ${{ inputs.token }}
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
        registry-url: "https://registry.npmjs.org"
    - name: Install Dependencies
      shell: bash
      run: |
        npm install -g @openapitools/openapi-generator-cli@2.5.2
    - name: Create generator config
      shell: bash
      working-directory: ${{inputs.sdk_output_directory}}
      run: |
        shopt -s extglob
        rm -r !(openapi.yaml)
        cp ../openapi-generator-config/openapitools-js.json openapitools.json
        cp -r ../openapi-generator-config/templates-js .
    - name: "Generate Node SDK"
      shell: bash
      working-directory: ${{inputs.sdk_output_directory}}
      run: |
        openapi-generator-cli generate --generator-key client -o src
    - name: "Clean up generator files"
      shell: bash
      working-directory: ${{inputs.sdk_output_directory}}/src
      run: |
        rm -rf openapitools.json templates-js .openapi-generator-ignore .openapi-generator git_push.sh
    - name: Commit SDK changes to the PR
      uses: EndBug/add-and-commit@v9
      if: ${{ inputs.dry-run != 'false' }}
      with:
        cwd: ${{inputs.sdk_output_directory}}
        add: src
        default_author: github_actions
        message: Update SDK based on openapi.yaml changes
