name: Build SDK JS

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch: {}

jobs:
  test-build-sdk-js:
    env:
      JS_SDK_TEST_REPOSITORY: "Kong/sdk-portal-js"
    runs-on: ubuntu-latest
    name: Test Build JS SDK on PR
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: ${{env.JS_SDK_TEST_REPOSITORY}}
          path: ${{github.workspace}}/sdk
      - uses: ./code-build-actions/build-js-sdk
        with:
          dry-run: 'true'
          app_directory: ${{ github.workspace }}
          sdk_output_directory: ${{github.workspace}}/sdk
          oas_file_location:  ${{github.workspace}}/sdk/openapi.yaml
          token: ${{secrets.GITHUB_TOKEN}}
