name: Build SDK JS

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch: {}

jobs:
  test-build-sdk-js:
    env:
      JS_SDK_TEST_REPOSITORY: "Kong/sdk-portal-js"
    runs-on: ubuntu-latest
    name: Test Build JS SDK on PR
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{env.JS_SDK_TEST_REPOSITORY}}
          path: ${{github.workspace}}/sdk
      - uses: ./code-build-actions/build-js-sdk
        with:
          dry-run: 'true'
          app_directory: ${{ github.workspace }}
          sdk_output_directory: ${{github.workspace}}/sdk
          token: ${{secrets.GITHUB_TOKEN}}

  notify-slack:
    name: Slack Notification
    permissions: 
      contents: read
    needs: [test-build-sdk-js]
    if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/workflow-notifications.yml
    with:
      workflow_name: "Build SDK JS Test Workflow"
      job_status: ${{ contains(needs.*.result, 'failure') && 'failure' || contains(needs.*.result, 'success') && 'success' || 'failure' }}
    secrets:
      SLACK_WEBHOOK_URL_NOTIFY: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_PUBLIC_SHARED_ACTIONS }}
      SLACK_WEBHOOK_URL_ALERT: ${{ secrets.SLACK_WEBHOOK_URL_ALERT_PUBLIC_SHARED_ACTIONS }}