name: SCA Directory Scan

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch: {}

jobs:
  test-sca-dir:
    runs-on: ubuntu-latest
    permissions:
      contents: write # publish sbom to GH releases/tag assets
      issues: read
      checks: write
      pull-requests: write
    name: Test Repository Scan
    steps:
        - uses: actions/checkout@v4
        - name: Scan Current Repository Directory
          id: scan-repo-dir
          uses: ./security-actions/sca
          with:
            dir: . # checkout path
            upload-sbom-release-assets: true