name: SCA Directory Scan

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch: {}

jobs:
  test-sca-dir:
    env:
      TEST_REPOSITORY: "${{github.repository_owner}}/insomnia"
    runs-on: ubuntu-latest
    permissions:
      contents: write # publish sbom to GH releases/tag assets
      issues: read
      checks: write
      pull-requests: write
    name: Test Repository Scan
    steps:
        - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
          with:
            repository: ${{env.TEST_REPOSITORY}}
            path: ${{env.TEST_REPOSITORY}}
        - name: Scan Directory
          id: scan-dir
          uses: ./security-actions/sca
          with:
            asset_prefix: test.insomnia
            dir: ${{env.TEST_REPOSITORY}}
            upload-sbom-release-assets: true
            fail_build: false
  
  notify-slack:
    name: Slack Notification
    permissions: 
      contents: read
    needs: [test-sca-dir]
    if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/workflow-notifications.yml
    with:
      workflow_name: "SCA Directory Scan Workflow"
      job_status: ${{ contains(needs.*.result, 'failure') && 'failure' || contains(needs.*.result, 'success') && 'success' || 'failure' }}
    secrets:
      SLACK_WEBHOOK_URL_NOTIFY: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_PUBLIC_SHARED_ACTIONS }}
      SLACK_WEBHOOK_URL_ALERT: ${{ secrets.SLACK_WEBHOOK_URL_ALERT_PUBLIC_SHARED_ACTIONS }}