name: SCA Directory Scan

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch: {}

jobs:
  test-sca-dir:
    env:
      TEST_REPOSITORY: "${{github.repository_owner}}/insomnia"
    runs-on: ubuntu-latest
    permissions:
      contents: write # publish sbom to GH releases/tag assets
      issues: read
      checks: write
      pull-requests: write
    name: Test Repository Scan
    steps:
        - uses: actions/checkout@v4
        - uses: actions/checkout@v4
          with:
            repository: ${{env.TEST_REPOSITORY}}
            path: ${{env.TEST_REPOSITORY}}
        - name: Scan Directory
          id: scan-dir
          uses: ./security-actions/sca
          with:
            asset_prefix: test.insomnia
            dir: ${{env.TEST_REPOSITORY}}
            upload-sbom-release-assets: true
            fail_build: false
