name: Test Download Build Push action Summary report

on:
  workflow_dispatch:

jobs:
  download-build-summary-report:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          context: .
          tags: user/app:latest
      - 
        name: Download assets
        uses: actions/download-artifact@v4
