name: Luacheck Test

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch: {}

jobs:
  test-lua-lint:
    env:
      TEST_REPOSITORY: "${{github.repository_owner}}/atc-router"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    name: Luacheck code analysis
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          repository: ${{env.TEST_REPOSITORY}}
          path: ${{env.TEST_REPOSITORY}}
      - uses: ./code-check-actions/lua-lint
        with:
          additional_args: '--no-default-config --config ${{env.TEST_REPOSITORY}}/.luacheckrc ${{env.TEST_REPOSITORY}}'
