name: Luacheck Test

on:
  pull_request:
    branches:
    - main
    paths:
    - code-check-actions/lua-*/**
  push:
    branches:
    - main
    tags:
    - '*'
    paths:
    - code-check-actions/lua-*/**
  workflow_dispatch: {}

jobs:
  test-lua-lint:
    env:
      TEST_REPOSITORY: "${{github.repository_owner}}/atc-router"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    name: Luacheck code analysis
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: ${{env.TEST_REPOSITORY}}
          path: ${{env.TEST_REPOSITORY}}
      - uses: ./code-check-actions/lua-lint
        with:
          additional_args: '--no-default-config --config ${{env.TEST_REPOSITORY}}/.luacheckrc ${{env.TEST_REPOSITORY}}'
