name: Luacheck Test

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch: {}

jobs:
  test-luacheck:
    env:
      LUA_TEST_REPOSITORY: "Kong/lua-resty-lmdb"
    runs-on: ubuntu-latest
    name: Test Lua code analysis check
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: ${{env.LUA_TEST_REPOSITORY}}
          path: ${{env.LUA_TEST_REPOSITORY}}
      - uses: ./code-check-actions/luacheck
        with:
          args: '--no-default-config --config ${{env.LUA_TEST_REPOSITORY}}/.luacheckrc ${{env.LUA_TEST_REPOSITORY}}'
