name: Luacheck Test

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch: {}

jobs:
  test-luacheck:
    env:
      LUA_TEST_REPOSITORY: "${{github.repository_owner}}/kong-ee"
    runs-on: ubuntu-latest
    name: Luacheck code analysis
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: ${{env.LUA_TEST_REPOSITORY}}
          token: ${{secrets.SCIMIA_BOT_GITHUB_TOKEN}}
          path: ${{env.LUA_TEST_REPOSITORY}}
      - uses: ./code-check-actions/luacheck
        with:
          additional_args: '--no-default-config --config ${{env.LUA_TEST_REPOSITORY}}/.luacheckrc ${{env.LUA_TEST_REPOSITORY}}'
