name: Rust SCA and Lint

on:
  release:
    types: [published]
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch: {}

jobs:
  test-rust-sca:
    env:
      RUST_TEST_REPOSITORY: "${{github.repository_owner}}/atc-router"
    outputs:
      grype-report: ${{ steps.rust_checks.outputs.grype-sarif-report }}
      sbom-spdx-report: ${{ steps.rust_checks.outputs.sbom-spdx-report }}
      sbom-cyclonedx-report: ${{ steps.rust_checks.outputs.sbom-cyclonedx-report }}
    runs-on: ubuntu-latest
    name: Rust code analysis and SCA checks
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: ${{env.RUST_TEST_REPOSITORY}}
          path: ${{env.RUST_TEST_REPOSITORY}}
      - uses: ./code-check-actions/rustcheck
        with:
          asset_prefix: ${{env.RUST_TEST_REPOSITORY}}
          dir: ${{ github.workspace }}/${{env.RUST_TEST_REPOSITORY}}