name: Secret Scan
permissions:
  contents: read
on:
  pull_request: {}
  push:
    branches: 
    - master
    - main
  workflow_dispatch: {}


jobs:
  secret-scan:
    name: secret-scan
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with: 
          fetch-depth: 0

      # Optional: Enable debug mode to troubleshoot or to get verbose logs from TruffleHog
      # To enable Debug mode, set env: ACTIONS_STEP_DEBUG: true
      - uses: ./security-actions/secret-scan
        name: Running Secret Scan using Trufflehog
        with:
          fail_on_findings: 'true'

  notify-slack:
    name: Slack Notification
    permissions: 
      contents: read
    needs: [secret-scan]
    if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/workflow-notifications.yml
    with:
      workflow_name: "Secret Scan Test Workflow"
      job_status: ${{ contains(needs.*.result, 'failure') && 'failure' || contains(needs.*.result, 'success') && 'success' || 'failure' }}
    secrets:
      SLACK_WEBHOOK_URL_NOTIFY: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_PUBLIC_SHARED_ACTIONS }}
      SLACK_WEBHOOK_URL_ALERT: ${{ secrets.SLACK_WEBHOOK_URL_ALERT_PUBLIC_SHARED_ACTIONS }}