name: Secret Scan
permissions:
  contents: read
on:
  pull_request: {}
  push:
    branches: 
    - master
    - main
  workflow_dispatch: {}


jobs:
  secret-scan:
    name: secret-scan
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with: 
          fetch-depth: 0  # TruffleHog's default behavior relies on commit history (base -> head), so full fetch-depth is required

      # Optional: Enable debug mode to troubleshoot or to get verbose logs from TruffleHog
      # To enable Debug mode, set env: ACTIONS_STEP_DEBUG: true
      - uses: ./security-actions/secret-scan
        name: Running Secret Scan using Trufflehog
        with:
          fail_on_findings: 'true'
        # env:
        #   ACTIONS_STEP_DEBUG: true  
