name: Semgrep SAST Test

on:
  release:
    types: [published]
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch:
    inputs:
      repository_name:
        required: true

jobs:
  test-semgrep-sast:
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    env:
      TEST_REPOSITORY: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.repository_name || format('{0}/kong-ee', github.repository_owner) }}
    runs-on: ubuntu-latest
    name: Luacheck code analysis
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: ${{env.TEST_REPOSITORY}}
          token: ${{secrets.SCIMIA_BOT_GITHUB_TOKEN}}
          path: ${{env.TEST_REPOSITORY}}
      - uses: ./code-check-actions/semgrep
        with:
          additional_args: '${{env.TEST_REPOSITORY}}'
