name: Semgrep SAST Test

on:
  release:
    types: [published]
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch:
    inputs:
      repository_name:
        required: false
        default: "Kong/kong-ee"

jobs:
  test-semgrep-sast:
    env:
      TEST_REPOSITORY: {{ github.event_name == "workflow_dispatch" ? github.event.inputs.repository_name : "Kong/kong-ee" }}
    runs-on: ubuntu-latest
    name: Luacheck code analysis
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: ${{env.TEST_REPOSITORY}}
          path: ${{env.TEST_REPOSITORY}}
      - uses: ./code-check-actions/semgrep
        with:
          additional_args: '${{env.TEST_REPOSITORY}}'
