name: Semgrep

on:
  pull_request: {}
  push:
    branches: 
    - master
    - main
  workflow_dispatch: {}


jobs:
  semgrep:
    name: SAST
    runs-on: ubuntu-22.04
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    env:
      TEST_REPOSITORY: "${{github.repository_owner}}/atc-router"
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{env.TEST_REPOSITORY}}
          token: ${{secrets.GITHUB_TOKEN}}
          path: ${{env.TEST_REPOSITORY}}
      - uses: ./security-actions/semgrep
        with:
          additional_config: '--config p/rust'
          codeql_upload: false
          fail_on_findings: false

  notify-slack:
    name: Slack Notification
    permissions: 
      contents: read
    needs: [semgrep]
    if: ${{ always() && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/workflow-notifications.yml
    with:
      workflow_name: "Semgrep Scan Test Workflow"
      job_status: ${{ contains(needs.*.result, 'failure') && 'failure' || contains(needs.*.result, 'success') && 'success' || 'failure' }}
    secrets:
      SLACK_WEBHOOK_URL_NOTIFY: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY_PUBLIC_SHARED_ACTIONS }}
      SLACK_WEBHOOK_URL_ALERT: ${{ secrets.SLACK_WEBHOOK_URL_ALERT_PUBLIC_SHARED_ACTIONS }}