# .github/workflows/slack-notification.yml
name: Slack Notification for all PSA Workflows

on:
  workflow_call:
    inputs:
      workflow_name:
        description: 'Name of the workflow that triggered this notification'
        required: true
        type: string
      job_status:
        description: 'Status of the job (success, failure, cancelled)'
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL_NOTIFY:
        description: 'Slack webhook URL for success notifications'
        required: true
      SLACK_WEBHOOK_URL_ALERT:
        description: 'Slack webhook URL for failure/alert notifications'
        required: true

jobs:
  notify:
    name: Send Slack Notification
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # Success Notification
      - name: Send Success Slack Notification
        if: ${{ inputs.job_status == 'success' }}
        uses: ./slack-actions/workflow-notification
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFY }}
          status: success
          payload: |
            {
              "text": "✅ ${{ inputs.workflow_name }} Success - ${{ github.repository }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "emoji": true,
                    "text": "✅ ${{ inputs.workflow_name }} Success"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Run #${{ github.run_number }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered By:*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.event.head_commit.message || 'No message available' }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${{ github.event.head_commit.author.name || github.actor }}"
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "🕐 Completed: ${{ github.event.head_commit.timestamp || github.run_started_at }} | Event: `${{ github.event_name }}` | Run ID: ${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
    
      # Failure Notification
      - name: Send Failure Slack Alert
        if: ${{ inputs.job_status == 'failure' }}
        uses: ./slack-actions/workflow-notification
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_ALERT }}
          status: failure
          payload: |
            {
              "text": "🚨 ${{ inputs.workflow_name }} FAILED - ${{ github.repository }} - Immediate attention required!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "emoji": true,
                    "text": "🚨 ${{ inputs.workflow_name }} FAILED"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "⚠️ *Action Required:* The ${{ inputs.workflow_name }} has failed and needs immediate attention."
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:*\n<${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Failed Run:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|🔍 View Logs - Run #${{ github.run_number }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Triggered By:*\n${{ github.actor }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:*\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.event.head_commit.message || 'No message available' }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${{ github.event.head_commit.author.name || github.actor }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*🔧 Quick Actions:*\n• <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View detailed logs>\n• <${{ github.server_url }}/${{ github.repository }}/actions|Check recent workflow history>"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "🕐 Failed: ${{ github.event.head_commit.timestamp || github.run_started_at }} | Event: `${{ github.event_name }}` | Please investigate ASAP"
                    }
                  ]
                }
              ]
            }
